server:  port: 9000

resilience4j:
  circuitbreaker:
    instances:
      outbound-service:        minimumNumberOfCalls: 10
        failureRateThreshold: 50        waitDurationInOpenState: 5s                automaticTransitionFromOpenToHalfOpenEnabled: true                permittedNumberOfCallsInHalfOpenState: 1                registerHealthIndicator: true
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED        ignore-exceptions:          - org.springframework.web.client.HttpClientErrorException  retry:    instances:      outbound-service:        max-attempts: 3        wait-duration: 200        ignore-exceptions:          - org.springframework.web.client.HttpClientErrorException
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
